### ISSUE TITLE
dr sr error

### ISSUE THREAD

**Issue by K0rkunc** [Mark-Wu/stm32_uart_dma_unknown_data_length#1]
if (huart1.Instance->SR & UART_FLAG_IDLE)
  {
    volatile uint32_t tmp;     /* Must be volatile to prevent optimizations */
    tmp = huart1.Instance->SR; /* Read status register for clear idle */
    tmp = huart1.Instance->DR; /* Read data register for clear idle */ 
    idle_flag = 1;
    UsartRxCheck();
    idle_flag = 0; 

dr and sr o member named sr and dr how to fix ?

**Comment by Mark-Wu** [comment]
I'm sorry. I can't get what's your mean. reading SR and DR is used for clearing the idle flag. you can check it on the TI website.
